function isodata()
{
    /*
    "A FAST IMPLEMENTATION OF THE ISODATA CLUSTERING ALGORITHM",
    NARGESS MEMARSADEGHI, DAVID M. MOUNT, NATHAN S. NETANYAHU, JACQUELINE LE MOIGNE, 2007
    */
    // TODO
}
fn.isodata = isodata;